### PR TITLE
update dependency versions

### PR DESCRIPTION
**Pull request by kghmanuel**
1. update dependencies.
2. audit findings mostly related to devDependencies

### CODE REVIEW

**Comment by grtjn** [comment]
Pagination bar looks wonky, otherwise great work! :)

**Comment by kghmanuel** [comment]
fixed. change is rather sizeable though. but the clash of dependency css is getting worse.

**Comment by grtjn** [comment]
Ah yes, that is a pain.. I restarted from scratch with my venom-ui-template, and switched to bootstrap 4 and scss there..

**Comment by grtjn** [comment]
Pagination looks normal again, awesome. Feel free to merge the PR.. ;-)

**Pull request merged**
